### ISSUE TITLE
1.13 Feedback

### ISSUE THREAD

**Issue by LlmDl** [TownyAdvanced/Towny#2995]
Rolling list of 1.13 Troubles:

- [x] as per WriteEscape: revert on unclaim of kelp/coral does not work
  - Could be because there's no block IDs at all for these.
  - Awaiting feedback from 0.93.0.2 testers.
- [x] Existing configs will need WaterMob removed from the town_mob_removal list.
   - Fixes fish from despawning when entering into towns.
- [x] All trapdoors except TRAP_DOOR are missing from the switchid list in the default config. 
   - They do not act like switches when added to the list though.
   - The brick tool shows the block being AIR, possibly will automatically fix itself once we build towny with a 1.13 bukkit.
- [x] Ticket #3010 - Regeneration of some things in the wilderness is not perfect.
- [x] Info Tool in Config will have to change from CLAY_BRICK to BRICK.
- [ ] As per Ticket #3050 - Wilderness ignoreIDs may not be working.
- [x] As per Ticket #3152  - A few things need to be added to the default switch/itemuse config lists.
- [x] As per Ticket #3056 - Test farm plots for pumpkins and melons.
- [x] As per Ticket #3034 - Tridents can disappear when thrown into PVP areas.
- [x] As per Ticket #3112 - Turtles/Dolphins need to be added to the protected animal list in the config.
- [x] As per Ticket #3136 - Rever on Unclaim can generate NPEs.

**Comment by ZackRuybal** [comment]
Fish are treated as hostile as per the report from one of the people that's actively testing Towny on 1.13.

**Comment by LlmDl** [comment]
@ZackRuybal I don't understand what you mean by that.

**Comment by ZackRuybal** [comment]
When the new fish (floating, swimming kind added in 1.13) enter a town, they despawn. They seem to be treated like hostile mobs inside of towns.

**Comment by LlmDl** [comment]
If the hostile mob list the config still says WaterMob it is likely that the new fish are part of that group. Existing configs will need the 2 guardian mobs added to that list and the watermob removed.

**Comment by TheFlagCourier** [comment]
Seems like Guardian and ElderGuardian are not even in the WaterMob class, but Dolphin, Squid, and the various fish are. (So Dolphins/Squid are probably also affected.)
(https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/WaterMob.html)

**Comment by LlmDl** [comment]
@TheFlagCourier you're right, but they are both considered Monsters so they'll be dealt with anyways if that's still in the config. I guess we just have to remove WaterMob. I wonder if they used to be considered watermobs or what.

**Comment by SmallSansSerif** [comment]
Noticed that the wilderness regeneration from creeper explosions in 1.13 seemed odd in that I was getting dead bushes appearing on the surface after regen. Also 'Nesseley' from Discord said about 1.13 regen:

"1.13 regen is bugged. It doesnt place back stairs the right way, upperslabs go to the ground aswell. You can report it on git, I forgot and aint home rn"

**Comment by LlmDl** [comment]
@SmallSansSerif It would be helpful for you to file a separate ticket in full so I know which version of Towny you're using, which version of spigot, etc. Don't skip the form. This ticket is for confirmed bugs and tracking their fixes.

**Comment by LlmDl** [comment]
Closing this cause we're done with it.
