### ISSUE TITLE
Give the bukkit events a structure

### ISSUE THREAD

**Issue by Articdive** [TownyAdvanced/Towny#3351]
For every event we add we should follow a system:
Pre...Events contain variables that can be changed by the event and are cancellable)
normal Events are final and are only used as a notification, contains getters ONLY, not cancellable.

PreObjectCreateEvent 
ObjectCreateEvent 

ObjectDeleteEvent 

PreObjectRenameEvent 
ObjectRenameEvent 

for towns and nations:
PreObjectChangeTagEvent 
ObjectChangeTagEvent

PreTownInviteResidentEvent
TownInviteResidentEvent

PreNationInviteTownEvent
NationInviteTownEvent

PreTownClaimEvent
TownClaimEvent

PreTownClaimEvent (cancellable and thrown when a mayor/ass removes a plot, also when /townyadmin unclaims something but if /ta unclaim --force then it calls TownDeletePlotEvent) 
TownUnclaimEvent 
TownDeletePlotEvent (thrown when a town gets disbanded)
Note: TownDeletePlotEvent sounds wrong, there might be better suggestions for the plot names.

Every object get's it's own subpackage for the events so
event.town
event.nation
and so on.
any other events like DisallowedPVPEvent
go into
event.general or just event.

Including this we should decide wether we want to call TownBlocks Plots or Plots TownBlocks and edit the eventnames according to that sense. I would vouch for it all being called Plot.

**Comment by LlmDl** [comment]
They're townblocks in the code which is what people are using to use our API. But they're (/plot)s to players who play the game. I'd lean towards using townblock as the convention.

Not sure if a TownDeletePlotEvent is needed as it's the same thing as a TownUnclaimEvent. Otherwise I'd be fine with putting the events into subfolders, it will further separate the old events that we deprecate.

**Comment by LlmDl** [comment]
While this sort of thing is done here some requested Events that should obviously happen at the same time as this ticket:

- [ ] #3323  Add Bukkit event for upkeep timer

- [ ] #3322 Add Bukkit events for economy actions (deposit/withdraw)

- [ ] #3121 Suggestion: PreRenameEvents, or make RenameEvents Cancellable

**Comment by LlmDl** [comment]
Closing this one, although things are a bit cluttered I believe that leaving the old events in place for a time would be crucial anyways. Rather than moving events around, perhaps a dedicated Towny API Events page in the wiki would be more useful in listing/organizing events - while also being able to properly guide developers in choosing their needed events.
